# hunspellminimal.cmake
#
# Usage:
#   include(hunspellminimal.cmake)
#   target_link_libraries(myapp PRIVATE hunspell)

CPMAddPackage(
    NAME hunspell_src
    GITHUB_REPOSITORY hunspell/hunspell
    GIT_TAG v1.7.2
    DOWNLOAD_ONLY YES
)

# ---------------------------------------------------
# Collect Hunspell sources
# ---------------------------------------------------

set(HUNSPELL_SRC_DIR ${hunspell_src_SOURCE_DIR}/src/hunspell)

file(GLOB HUNSPELL_SOURCES
    ${HUNSPELL_SRC_DIR}/*.cxx
    ${HUNSPELL_SRC_DIR}/*.c
)

set(HUNSPELL_HEADERS
    ${HUNSPELL_SRC_DIR}/affentry.hxx
    ${HUNSPELL_SRC_DIR}/atypes.hxx
    ${HUNSPELL_SRC_DIR}/baseaffix.hxx
    ${HUNSPELL_SRC_DIR}/csutil.hxx
    ${HUNSPELL_SRC_DIR}/filemgr.hxx
    ${HUNSPELL_SRC_DIR}/hashmgr.hxx
    ${HUNSPELL_SRC_DIR}/hunspell.hxx
    ${HUNSPELL_SRC_DIR}/hunspell.h
    ${HUNSPELL_SRC_DIR}/langnum.hxx
    ${HUNSPELL_SRC_DIR}/phonet.hxx
    ${HUNSPELL_SRC_DIR}/replist.hxx
    ${HUNSPELL_SRC_DIR}/suggestmgr.hxx
    ${HUNSPELL_SRC_DIR}/w_char.hxx
)

## make config files
set(GEN ${CMAKE_CURRENT_BINARY_DIR}/hunspell_gen)
file(MAKE_DIRECTORY ${GEN})

# Generate required headers
file(WRITE ${GEN}/config-hunspell.h "
/* Minimal config-hunspell.h generated by CMake */

#include <QLoggingCategory>

#ifndef CONFIG_HUNSPELL_H
#define CONFIG_HUNSPELL_H

/* Whether to use iconv */
#define HAVE_ICONV 1

/* Enable warnings */
#define HUNSPELL_WARNING_ON 1

/* Allow regex (grep-like) */
#define HAVE_REPL 1

/* Define inline */
#define HUNSPELL_USE_INLINE 1

/* Windows-specific tweaks */
#if defined(_WIN32)
  #define WIN32 1
  #define W32 1
  #define HAVE_WINDOWS_H 1
  #define HAVE_IO_H 1
#endif

#endif /* CONFIG_HUNSPELL_H */
")

# ---------------------------------------------------
# Create static library
# ---------------------------------------------------

add_library(hunspell_minimal STATIC ${HUNSPELL_SOURCES} ${HUNSPELL_HEADERS})

target_include_directories(hunspell_minimal PUBLIC
    ${HUNSPELL_SRC_DIR}
)
target_include_directories(hunspell_minimal PRIVATE
    ${HUNSPELL_SRC_DIR}
    ${GEN}                    # generated headers (export, debug)
)

target_compile_definitions(hunspell_minimal PRIVATE
    HUNSPELL_STATIC
)

# Optional compiler settings
target_compile_features(hunspell_minimal PRIVATE cxx_std_17)

# Tune warnings (optional)
if(MSVC)
    target_compile_options(hunspell_minimal PRIVATE /W3)
else()
    target_compile_options(hunspell_minimal PRIVATE -Wall -Wextra -Wno-unused-parameter)
endif()

add_library(hunspell::minimal ALIAS hunspell_minimal)
